### ISSUE TITLE
How to use Indicator in your library?

### ISSUE THREAD

**Issue by tellfa** [demoNo/AutoScrollViewPager#4]
I want use your library, i should show Indicator  in viewPager.
for set Indicator  i want use below code in adapter.
```
   @Override
    public int getCount() {
        return model.size();
    }
```

but when use above code in adapter, show many bugs in viewpager! 

how can i use this?

**Comment by demoNo** [comment]
Hi @tellfa what indicator are you use, plz post the source code that I can find out the problem.

**Comment by demoNo** [comment]
besides, if your adapter extends InfinitePagerAdapter, you should override getItemCount() instead of getCount().

**Comment by siralam** [comment]
I think this library does not support indicator (at least easily) because its approach is faking a very large number of items in adapter.

If you try to add an indicator to it, you will find that the number of indicators simply break your screen...
