### ISSUE TITLE
Selected item page skip zero index in view pager while moving as per given interval 

### ISSUE THREAD

**Issue by iamavdhesh** [demoNo/AutoScrollViewPager#7]
` <com.github.demono.AutoScrollViewPager
                android:id="@+id/vpHomeBanner"
                android:layout_width="match_parent"
                android:layout_height="@dimen/dp_150"
                app:stopWhenTouch="true"
                android:layout_marginTop="@dimen/dp_4"
                app:slideDirection="right"
                app:slideInterval="1000"
                app:cycle="true"
                app:slideDuration="1000"/>`

View Pager skip zero index for selection of given time interval

**Comment by demoNo** [comment]
Now it not support initial delay for zero index, you can implement it by clone.
